apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-plexus
  labels:
    app: hello-plexus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-plexus
  template:
    metadata:
      labels:
        app: hello-plexus
    spec:
      containers:
        - name: hello-plexus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
